-- Recreate profile_summaries table after it was dropped
-- Migration: 20250119100000_recreate_profile_summaries.sql

-- Drop the table if it exists (in case it's partially there)
DROP TABLE IF EXISTS profile_summaries CASCADE;

-- Profile summaries (generated by LLM)
CREATE TABLE profile_summaries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID UNIQUE NOT NULL REFERENCES profiles(user_id) ON DELETE CASCADE,
  summary_json JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for faster lookups
CREATE INDEX idx_profile_summaries_user_id ON profile_summaries(user_id);

-- Row-Level Security Policies
ALTER TABLE profile_summaries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own profile summary"
  ON profile_summaries FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can manage profile summaries"
  ON profile_summaries FOR ALL
  USING (auth.role() = 'service_role');

-- Trigger for updating updated_at timestamp
CREATE TRIGGER update_profile_summaries_updated_at
  BEFORE UPDATE ON profile_summaries
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

